# Name of your server
server-name: "MyServer"
# Description of your server
server-description: "server from hcf ._."
# Color server
server-color: "ยง6"

# Discord
webhook-url: ""
webhook-check: false

# GUI
gui-enabled: true

# Cooldowns
COOLDOWN:
 ENDERPEARL: 30
 COMBAT_TAG: 20
 GAPPLE: 10
 ARCHERTAG: 10

# Special Items
special-items:
 BowSpider:
  name: ""
  lores: ""

factions:
 playersMax: 4

commands-cooldown:
 report: 45
 logout: 30
 
blocked-items: []
blocked-blocks: []
